### ISSUE TITLE
observing error No module named api

### ISSUE THREAD

**Issue by vasujammula** [aeroxis/sultan#40]
Traceback (most recent call last):
  File "su.py", line 3, in <module>
    from sultan.api import *
  File "/var/www/html/sultan.py", line 3, in <module>
ImportError: No module named api

>>> import sultan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/html/sultan.py", line 3, in <module>
ImportError: No module named api
>>>
>>> from sultan.api import Sultan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/html/sultan.py", line 3, in <module>
ImportError: No module named api

**Comment by davydany** [comment]
Did you run `pip install sultan`? It doesn't seem like you have sultan installed. 

If that doesn't solve it, run these, and let me know the output:

```
pip --version
```

List what modules are installed:

```
pip freeze
```

And where your python interpreter is:

```
which python
```

**Comment by davydany** [comment]
I'm closing this since there was no response.
